<?php

/**
 * Static class that contains context info and data about the currently 
 * called web service. 
 */
class WpakWebServiceContext {

	/**
	 * App ID (WP post ID) for which the current web service is called
	 * @var int 
	 */
	public static $current_app_id = 0;
	
	/**
	 * App slug (WP post post_name) for which the current web service is called
	 * @var string 
	 */
	public static $current_app_slug = '';
	
	/**
	 * Current web service CRUD action : create, read, read_one, update or delete.
	 * @var string 
	 */
	public static $crud_action = '';
			
	/**
	 * Retrieves params that are sent by the client app when it calls
	 * a webservice.
	 * @return Array Params sent by the client app when calling the web service
	 */
	public static function getClientAppParams() {
		$client_app_params = array();

		//For now we only handle params for "read" type web services :
		if ( self::$crud_action == 'read' || self::$crud_action == 'read_one' ) {
			$client_app_params = $_GET;
			//Note : here, $_GET is generated by the client app that sends data
			//along with its web service query, so it can contain array passed
			//with the format param[]=1&param[]=2.
			//So we can't really sanitize $_GET here as we don't know what
			//it will contain (strings/ints or arrays).
		}

		return $client_app_params;
	}

	/**
	 * Retrieves a given params that is sent by the client app when it calls
	 * a webservice.
	 * @return Array Param sent by the client app when calling the web service
	 */
	public static function getClientAppParam( $key ) {
		$client_app_param_value = null;

		//For now we only handle params for "read" type web services :
		if ( self::$crud_action == 'read' || self::$crud_action == 'read_one' ) {
			if ( isset( $_GET[$key] ) ) {
				$client_app_param_value = $_GET[$key];
			}
		}

		return $client_app_param_value;
	}
	
}

